-- Migration: 0001_init
-- Generated by: prisma migrate diff --from-empty --to-schema
-- Run this AFTER setting a real DATABASE_URL:
--   npx prisma migrate deploy
--
-- ─────────────────────────────────────────────
-- ENUMS
-- ─────────────────────────────────────────────

CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'MANAGER', 'EMPLOYEE');

CREATE TYPE "SeatType" AS ENUM (
  'REGULAR',
  'HOT_DESK',
  'ACCESSIBLE',
  'PRIVATE',
  'MEETING_ROOM'
);

CREATE TYPE "SeatStatus" AS ENUM (
  'AVAILABLE',
  'OCCUPIED',
  'RESERVED',
  'MAINTENANCE'
);

-- ─────────────────────────────────────────────
-- TENANTS
-- ─────────────────────────────────────────────

CREATE TABLE "tenants" (
  "id"        TEXT         NOT NULL,
  "name"      TEXT         NOT NULL,
  "slug"      TEXT         NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "tenants_slug_key" ON "tenants"("slug");

-- ─────────────────────────────────────────────
-- PROJECTS
-- ─────────────────────────────────────────────

CREATE TABLE "projects" (
  "id"         TEXT         NOT NULL,
  "tenantId"   TEXT         NOT NULL,
  "code"       TEXT         NOT NULL,
  "name"       TEXT         NOT NULL,
  "lead"       TEXT         NOT NULL,
  "targetZone" TEXT         NOT NULL,
  "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"  TIMESTAMP(3) NOT NULL,

  CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "projects_tenantId_code_key" ON "projects"("tenantId", "code");
CREATE INDEX "projects_tenantId_idx" ON "projects"("tenantId");

ALTER TABLE "projects"
  ADD CONSTRAINT "projects_tenantId_fkey"
  FOREIGN KEY ("tenantId") REFERENCES "tenants"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ─────────────────────────────────────────────
-- USERS
-- ─────────────────────────────────────────────

CREATE TABLE "users" (
  "id"           TEXT         NOT NULL,
  "tenantId"     TEXT         NOT NULL,
  "employeeCode" TEXT         NOT NULL,
  "name"         TEXT         NOT NULL,
  "email"        TEXT         NOT NULL,
  "role"         "UserRole"   NOT NULL DEFAULT 'EMPLOYEE',
  "projectId"    TEXT,
  "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"    TIMESTAMP(3) NOT NULL,

  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "users_tenantId_employeeCode_key" ON "users"("tenantId", "employeeCode");
CREATE UNIQUE INDEX "users_tenantId_email_key" ON "users"("tenantId", "email");
CREATE INDEX "users_tenantId_idx" ON "users"("tenantId");
CREATE INDEX "users_projectId_idx" ON "users"("projectId");

ALTER TABLE "users"
  ADD CONSTRAINT "users_tenantId_fkey"
  FOREIGN KEY ("tenantId") REFERENCES "tenants"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "users"
  ADD CONSTRAINT "users_projectId_fkey"
  FOREIGN KEY ("projectId") REFERENCES "projects"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ─────────────────────────────────────────────
-- SEATS
-- ─────────────────────────────────────────────

CREATE TABLE "seats" (
  "id"        TEXT         NOT NULL,
  "tenantId"  TEXT         NOT NULL,
  "label"     TEXT         NOT NULL,
  "floor"     INTEGER      NOT NULL,
  "zone"      TEXT         NOT NULL,
  "row"       INTEGER      NOT NULL,
  "col"       INTEGER      NOT NULL,
  "type"      "SeatType"   NOT NULL DEFAULT 'REGULAR',
  "status"    "SeatStatus" NOT NULL DEFAULT 'AVAILABLE',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "seats_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "seats_tenantId_floor_zone_row_col_key" ON "seats"("tenantId", "floor", "zone", "row", "col");
CREATE INDEX "seats_tenantId_floor_zone_idx" ON "seats"("tenantId", "floor", "zone");
CREATE INDEX "seats_status_idx" ON "seats"("status");

ALTER TABLE "seats"
  ADD CONSTRAINT "seats_tenantId_fkey"
  FOREIGN KEY ("tenantId") REFERENCES "tenants"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ─────────────────────────────────────────────
-- SEAT ASSIGNMENTS
-- ─────────────────────────────────────────────

CREATE TABLE "seat_assignments" (
  "id"         TEXT         NOT NULL,
  "userId"     TEXT         NOT NULL,
  "seatId"     TEXT         NOT NULL,
  "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "releasedAt" TIMESTAMP(3),
  "assignedBy" TEXT,
  "notes"      TEXT,

  CONSTRAINT "seat_assignments_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "seat_assignments_userId_key" ON "seat_assignments"("userId");
CREATE UNIQUE INDEX "seat_assignments_seatId_key" ON "seat_assignments"("seatId");
CREATE INDEX "seat_assignments_seatId_idx" ON "seat_assignments"("seatId");
CREATE INDEX "seat_assignments_assignedAt_idx" ON "seat_assignments"("assignedAt");

ALTER TABLE "seat_assignments"
  ADD CONSTRAINT "seat_assignments_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "users"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "seat_assignments"
  ADD CONSTRAINT "seat_assignments_seatId_fkey"
  FOREIGN KEY ("seatId") REFERENCES "seats"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
